#!/bin/bash
claar
# Verifiacando se é o superusuario
if { $EUID -ne 0 }
then
echo "Você deve ser superusuário!>
exit 1
fi

echo "-------------------------------------"
echo "  GERENCIADOR DE CONTAS DE USUÁRIO   "
echo "-------------------------------------"

read -p "Digite o prefixo para os nomes dos novos usuários: " PREFIXO
for 1 in {1..10}
do
	NOVO_USUARIO=PREFIXO$i
	if [ -z $NOVO_USUARIO ]
	then
		echo "Você não informou o nome do novo usuário"
		exit 1
	fi

read -p "Digite o nome de novo usuário:" NOVO_USUARIO

if { -z "$NOVO_USUARIO" }; then
   echo "Erro: O nome do usuário não pode ser vazio."
   exit 1
fi

id "$NOVO_USUARIO" &> /dev/null

if { -z "$NOVO_USUARIO" }; then
echo "Erro: O usuário '$NOVO_USUARIO' ja existe no sistema!"
   exit 1
fi

SENHA_PADRAO="Mudar@123"

useradd -m -s /bin/bash "$NOVO_USUARIO" 

if { &? -eq 0 }; then
echo "$NOVO_USUARIO:$SENHA_PADRAO" | chpasswd

        if { $? -eq 0 }; then
        chage -d 0 "$NOVO_USUARIO"

        echo "---------------------------------------------------------------->
        echo "Sucesso: Conta '$NOVO_USUARIO' criada corretamente."
        echo "AVISO: O usuário seá forçado a trocar a senha no 1º login."
     else
        echo "Erro ao Definir a senha padrão."
     fi
  else
        echo "Erro Crítico ao tentar criar a conta no sistema."
done
